services:
  customer-service:
    build: ./customer-service
    ports:
      - "8080:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/customerdb
      - SPRING_DATASOURCE_USERNAME=insureflow
      - SPRING_DATASOURCE_PASSWORD=insureflow

    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    restart: always
    shm_size: 128mb

    environment:
      POSTGRES_DB: customerdb
      POSTGRES_USER: insureflow
      POSTGRES_PASSWORD: insureflow
    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U insureflow -d customerdb" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: